wandb_version: 1

K:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 32
context_size:
  desc: null
  value: 8
dropout:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 2000
experimental_dataset:
  desc: null
  value: mouse_3regions_raw_and_map_reg_fold0
freeze_config:
  desc: null
  value: none
hidden_units:
  desc: null
  value: 96
learning_rate:
  desc: null
  value: 0.0002951481767707875
num_blocks:
  desc: null
  value: 2
optimizer:
  desc: null
  value: adam
pretrain_run:
  desc: null
  value: ga4p9e9u
pretrain_set:
  desc: null
  value: dog
weight_decay:
  desc: null
  value: 6.1221740028899216e-06
_wandb:
  desc: null
  value:
    python_version: 3.8.8
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717701320.945708
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 23
      - 37
      4: 3.8.8
      5: 0.15.12
      8:
      - 1
      - 5
      13: linux-x86_64
